# Generated by Django 4.1.7 on 2023-03-26 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rating_comment',
            new_name='comment_rating',
        ),
    ]
