# Generated by Django 4.1.7 on 2023-03-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0002_rename_rating_comment_comment_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='selection_field',
            field=models.CharField(choices=[('article', 'статья'), ('news', 'новости')], default='NW', max_length=10),
        ),
    ]
