# Generated by Django 4.1.7 on 2023-03-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0003_alter_post_selection_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(default='comment'),
        ),
    ]
